### ISSUE TITLE
2020-09-09 Agenda

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/introduction-machine-learning#20]
**Items**
- [x] Project board up 
- [x] Completion mark 
- [x] Go over [feedback](https://github.com/UBC-MDS/introduction-machine-learning/issues/19)
- [x] Status on assignment2 
- [x] Elijah tests/dockerfile/amendments

**Comment by mgelbart** [comment]
- Reschedule/cancel Monday's meeting

**Comment by kvarada** [comment]
- Using some exercises in the online course as in-class activities in 571.
